SELECT
    ID,
    EXTERNAL_ID AS PATIENT_ID,
    STEPS,
    TRY_TO_TIMESTAMP_TZ(SUBMISSION_TIME, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM') AS SUBMITTED_AT,
    TRY_TO_TIMESTAMP_TZ(SUBMISSION_TIME, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM') AS UPDATED_AT
FROM ref('stg_steps')