[project]
name = "caspar-health-technical-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.8.9",
    "dbt-postgres>=1.8.2",
]
